image: eclipse-temurin:8-jdk
stages:
  - test

java-test:
  stage: test
  script:
    - apt-get update && apt-get install -y graphviz 
    - chmod +x build-targets.sh
    - chmod +x build-analysis.sh
    - chmod +x run-analysis-one.sh
    - chmod +x run-analysis.sh
    - ./run-analysis.sh
  artifacts:
    paths:
    - target1-pub/BasicTest.fun1.fulloutput.txt
    - target1-pub/BasicTest.fun1.output.txt
    - target1-pub/BasicTest.fun2.fulloutput.txt
    - target1-pub/BasicTest.fun2.output.txt
    expire_in: 1 week