image: eclipse-temurin:8-jdk
stages:
  - test

java-test:
  stage: test
  script:
    - apt-get update && apt-get install -y graphviz 
    - chmod +x build-targets.sh
    - chmod +x build-analysis.sh
    - chmod +x run-analysis-one.sh
    - chmod +x run-analysis.sh
    - chmod +x cleanup.sh
    - ./run-analysis.sh